"""add user role and active

Revision ID: 09831a672b0c
Revises: de20a5b3645c
Create Date: 2026-07-08 17:15:58.882658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09831a672b0c'
down_revision: Union[str, Sequence[str], None] = 'de20a5b3645c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE users SET role='player'"
    )

    op.execute(
        "UPDATE users SET is_active=true"
    )

    op.alter_column(
        'users',
        'role',
        nullable=False
    )

    op.alter_column(
        'users',
        'is_active',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
